FROM ubuntu:latest
MAINTAINER Artur Tarverdyan

RUN apt-get update -y

RUN apt-get upgrade -y

RUN apt-get install -y nano git curl zip

RUN apt-get install -y apache2

RUN apache2 -v

RUN apt-get install -y mysql-client

RUN dpkg --get-selections | grep mysql

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get install -y php libapache2-mod-php php-mysql php7.2-cli php7.2-curl php7.2-gd php7.2-mbstring php7.2-mysql php7.2-xml

COPY servername.conf /etc/apache2/conf-available/

RUN a2enconf servername

COPY dir.conf /etc/apache2/mods-enabled/

COPY index.html /var/www/html/

COPY style.css /var/www/html/

COPY script.js /var/www/html/

RUN service apache2 restart

CMD ["/usr/sbin/apachectl", "-D", "FOREGROUND"]

EXPOSE 80

